source 'https://rubygems.org'

gem 'rake'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'faker'
gem 'site_prism'
gem 'selenium-webdriver'
gem 'ruby-gmail'
gem 'poltergeist'
gem 'activesupport', '~>3.2.18'
gem 'eyes_selenium'
gem 'chronic'
gem 'faraday'